apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp

spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.0.0 

  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.0.0

    spec:
      containers:
        - name: mynginx-container
          image: nginx
          ports:
            - containerPort: 8080
