apiVersion: v1
kind: Pod


metadata:
  name:  onepod
  labels:
    name: onepod


spec:
  containers:
  - name: first-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
