apiVersion: v1
kind: ReplicationController


metadata:
  name: myrc


spec:
  replicas: 3
  selector:
    app: myrc

  template:
    metadata:
      labels:
        app: myrc

    spec:
      containers:
        - name: rc-container
          image: nginx
          ports:
            - containerPort: 80
