apiVersion: v1
kind: ReplicationController

metadata:
 name: two-rc

spec:
  replicas: 3
  selector:
    app: two-rc

  template:
    metadata:
      labels:
        app: two-rc

    spec:
      containers:
       - name: second-container
         image: nginx
         ports:
           - containerPort: 8081   


   



